{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "inputWidgets": {},
     "nuid": "89450337-985b-41a3-bc5a-f0b530fd9735",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "from fastapi import FastAPI, HTTPException\n",
    "from pydantic import BaseModel\n",
    "from functools import wraps\n",
    "from typing import Dict, Optional\n",
    "import json\n",
    "\n",
    "# Initialize FastAPI app\n",
    "app = FastAPI()\n",
    "\n",
    "# In-memory dictionary to store books\n",
    "books: Dict[int, dict] = {}\n",
    "\n",
    "# Pydantic Book model for validation\n",
    "class Book(BaseModel):\n",
    "    id: int\n",
    "    title: str\n",
    "    author: str\n",
    "    year: int\n",
    "    genre: Optional[str] = None\n",
    "\n",
    "# Decorator: Validate Data\n",
    "def validate_title_case(func):\n",
    "    @wraps(func)\n",
    "    def wrapper(*args, **kwargs):\n",
    "        # Perform title validation if it exists in input\n",
    "        if \"book\" in kwargs:\n",
    "            book = kwargs[\"book\"]\n",
    "            if not book.title[0].isupper():\n",
    "                raise HTTPException(status_code=400, detail=\"Book title must start with an uppercase letter.\")\n",
    "        return func(*args, **kwargs)\n",
    "    return wrapper\n",
    "\n",
    "# Decorator: Log API Actions\n",
    "def log_action(func):\n",
    "    @wraps(func)\n",
    "    def wrapper(*args, **kwargs):\n",
    "        print(f\"API call: {func.__name__}\")  # Log the name of the function being accessed\n",
    "        return func(*args, **kwargs)\n",
    "    return wrapper\n",
    "\n",
    "\n",
    "# Route 1: Add a new book\n",
    "@app.post(\"/books\")\n",
    "@validate_title_case\n",
    "@log_action\n",
    "def add_book(book: Book):\n",
    "    if book.id in books:\n",
    "        raise HTTPException(status_code=400, detail=\"Book with this ID already exists.\")\n",
    "    books[book.id] = book.dict()\n",
    "    return {\"message\": f\"Book '{book.title}' added successfully\"}\n",
    "\n",
    "\n",
    "# Route 2: Retrieve all books\n",
    "@app.get(\"/books\")\n",
    "@log_action\n",
    "def get_books():\n",
    "    return {\"books\": list(books.values())}\n",
    "\n",
    "\n",
    "# Route 3: Retrieve a specific book by ID\n",
    "@app.get(\"/books/{id}\")\n",
    "@log_action\n",
    "def get_book(id: int):\n",
    "    if id not in books:\n",
    "        raise HTTPException(status_code=404, detail=\"Book not found.\")\n",
    "    return books[id]\n",
    "\n",
    "\n",
    "# Route 4: Update book details\n",
    "@app.put(\"/books/{id}\")\n",
    "@validate_title_case\n",
    "@log_action\n",
    "def update_book(id: int, book: Book):\n",
    "    if id not in books:\n",
    "        raise HTTPException(status_code=404, detail=\"Book not found.\")\n",
    "\n",
    "    books[id] = book.dict()\n",
    "    return {\"message\": f\"Book '{book.title}' updated successfully\"}\n",
    "\n",
    "\n",
    "# Route 5: Delete a book by ID\n",
    "@app.delete(\"/books/{id}\")\n",
    "@log_action\n",
    "def delete_book(id: int):\n",
    "    if id not in books:\n",
    "        raise HTTPException(status_code=404, detail=\"Book not found.\")\n",
    "    \n",
    "    deleted_book = books.pop(id)\n",
    "    return {\"message\": f\"Book '{deleted_book['title']}' deleted successfully\"}\n",
    "\n",
    "\n",
    "# Route 6: Export books to JSON file\n",
    "@app.get(\"/export-json\")\n",
    "@log_action\n",
    "def export_books_to_json():\n",
    "    with open(\"exported_books.json\", \"w\") as file:\n",
    "        json.dump(list(books.values()), file, indent=4)\n",
    "    return {\"message\": \"Books exported to 'exported_books.json' successfully\"}\n",
    "\n",
    "\n",
    "# Route 7: Import books from JSON file\n",
    "@app.post(\"/import-json\")\n",
    "@log_action\n",
    "def import_books_from_json():\n",
    "    try:\n",
    "        with open(\"exported_books.json\", \"r\") as file:\n",
    "            imported_books = json.load(file)\n",
    "            for book_data in imported_books:\n",
    "                books[book_data[\"id\"]] = book_data\n",
    "        return {\"message\": \"Books imported successfully!\"}\n",
    "    except FileNotFoundError:\n",
    "        raise HTTPException(status_code=400, detail=\"No exported JSON file found.\")\n",
    "\n",
    "\n",
    "# Route 8: Root endpoint (Welcome message)\n",
    "@app.get(\"/\")\n",
    "def root():\n",
    "    return {\"message\": \"Welcome to the Book Management API! Use the available endpoints to manage your books.\"}"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": {
    "hardware": {
     "accelerator": null,
     "gpuPoolId": null,
     "memory": null
    }
   },
   "dashboards": [],
   "environmentMetadata": {
    "base_environment": "",
    "environment_version": "4"
   },
   "inputWidgetPreferences": null,
   "language": "python",
   "notebookMetadata": {
    "mostRecentlyExecutedCommandWithImplicitDF": {
     "commandId": 8838225170104055,
     "dataframes": [
      "_sqldf"
     ]
    },
    "pythonIndentUnit": 4
   },
   "notebookName": "main.py",
   "widgets": {}
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}